### PR TITLE
Enhancement in the CreateWindowsService task type of the Automatic service initialization (Delayed Start)

### PR DESCRIPTION
**Pull request by juliorovesta**
Hi!

I would like to contribute by adding an enhancement to the CreateWindowsService task in order to enable the type of initialization of the Automatic (Delayed Start) service, since I am in need of this.

I'm generating a pull request with this enhancement.

### CODE REVIEW

**Comment by juliorovesta** [comment]
Hi!

I would like to contribute by adding an enhancement to the CreateWindowsService task in order to enable the type of initialization of the Automatic (Delayed Start) service, since I am in need of this.

**Comment by chrisism** [comment]
Thank you

**Comment by juliorovesta** [comment]
Thank you.
Could you generate a new version of the package in the marketplace including these improvements?

**Comment by chrisism** [comment]
And it is there

**Comment by juliorovesta** [comment]
Thank you my friend!

**Pull request merged**
